### ISSUE TITLE
Hope more document

### ISSUE THREAD

**Issue by ByZhouhang** [pschiffe/pcs#3]
I'm new to Pacemaker and Corosync, and  glad  found your repository to help me build my environment quickly. But I find some points that I don't understand, look forward to your reply:

1. There doesn't seem to be a command to install Pacemaker, pcsd Web UI  in the dockerfile ,Will installing pcs automatically install Pacemaker, pcsd?

2. The official mssql documentation says that there should be ocf:mssql:ag resources, but I only found pgsql or mysql in it,  there is no mssql  ，Is it the reason for the docker image?
[mircorsoft doc](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-pacemaker?view=sql-server-ver16&tabs=ubuntu)

3. Can I use your image, using docker-compose, to create three containers on one host, simulating three nodes?

4、Is there a recommended introduction blog for pcsd web UI operations, or a demo for practical failover?

**Comment by pschiffe** [comment]
Hi @ByZhouhang,

1. yes, pacemaker and pcsd are installed as a dependency to the pcs, you can see all installed packages here: https://github.com/pschiffe/pcs/actions/runs/11630462771/job/32389453511#step:6:255
2. `ocf:mssql:ag` is part of the `mssql-server-ha` package, however that requires whole `mssql-server`, so it's not included in this docker image
3. maybe it's possible, but these tools are designed to manage the whole VM / OS, so I didn't try to explore a docker only setup
4. not sure about the web ui, but in general, it's good to start here https://clusterlabs.org/projects/pacemaker/doc/index.php

**Comment by ByZhouhang** [comment]
> Hi @ByZhouhang,
> 
> 1. yes, pacemaker and pcsd are installed as a dependency to the pcs, you can see all installed packages here: https://github.com/pschiffe/pcs/actions/runs/11630462771/job/32389453511#step:6:255
> 2. `ocf:mssql:ag` is part of the `mssql-server-ha` package, however that requires whole `mssql-server`, so it's not included in this docker image
> 3. maybe it's possible, but these tools are designed to manage the whole VM / OS, so I didn't try to explore a docker only setup
> 4. not sure about the web ui, but in general, it's good to start here https://clusterlabs.org/projects/pacemaker/doc/index.php


I tried docker-compose to simulate three nodes, it was ok on my virtual machine, but the same file on the cloud server, after setting up the hacluster account password, the login UI always prompts Incorrect login credentials， it's weird，here is the file content

```
version: "3.9"

services:
  pacemaker-node1:
    image: pschiffe/pcs
    container_name: pacemaker-node1
    hostname: pacemaker-node1
    privileged: true
    ports:
      - "32224:2224"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/docker.sock:/var/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
  pacemaker-node2:
    image: pschiffe/pcs
    container_name: pacemaker-node2
    hostname: pacemaker-node2
    privileged: true
    ports:
      - "32225:2224"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/docker.sock:/var/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
  pacemaker-node3:
    image: pschiffe/pcs
    container_name: pacemaker-node3
    hostname: pacemaker-node3
    privileged: true
    ports:
      - "32226:2224"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/docker.sock:/var/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
```
![image](https://github.com/user-attachments/assets/9456e32a-e266-4a36-8c48-0accb45172d8)

For beginners, the most important thing to practice is to see the process of switching resources in Pacemaker, can you provide a little detailed demo process in the documentation when you have time? For example, what kind of environment operation walkthrough should be prepared for virtual IP and docker resource image in the documentation, and see what the specific effect is

Thank you so much for taking the time to reply, it helped me a lot
